name: Test
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - uses: ./.github/actions/build-packages
      - name: Lint files
        run: pnpm run lint
      - name: Type check
        run: pnpm run type-check
  test:
    runs-on: ${{ matrix.os }}
    needs:
      - lint
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [ubuntu-20.04, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/setup-deno
      - uses: ./.github/actions/build-packages
      # https://github.com/actions/virtual-environments/issues/712#issuecomment-613004302
      - name: Set TEMP on Windows
        run: echo "TEMP=$env:USERPROFILE\AppData\Local\Temp" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        if: ${{ runner.os == 'Windows' }}
      - uses: azure/setup-kubectl@v3
        with:
          version: v1.23.1
      - uses: azure/setup-helm@v3
        with:
          version: 3.10.2
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/setup-kustomize
      - name: Run unit tests
        run: pnpm run test:unit --coverage
      - name: Run integration tests
        run: pnpm run test:integration
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  test-browser:
    runs-on: ubuntu-20.04
    needs:
      - lint
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - uses: ./.github/actions/build-packages
      - name: Run browser tests
        run: pnpm run test:browser
